DOCS-659: Improve robot page
viamrobotics/docs pull request #1057
Opened 2023-04-17 15:11 UTC by npentrel

2023-04-17 16:04 UTC, sguequierre requested changes

2023-04-17 16:04 UTC, sguequierre commented on docs/manage/fleet/robots.md
> +{{<gif webm_src="../../img/load-prev-config.webm" mp4_src="../../img/load-prev-config.mp4" alt="Load a previous config from the UI">}}
Unfortunately this gif looks super blurry when 
I load it on the staging link-- maybe try reuploading?

2023-04-17 16:04 UTC, sguequierre commented on docs/manage/fleet/robots.md
> +??
```suggestion
```

2023-04-18 14:12 UTC, sguequierre approved these changes
lgtm but you probably want to change capitalization on the tabs/sub-tabs (**CONFIG** -> **config** etc.) before merging!

2023-04-18 14:16 UTC, npentrel commented on docs/manage/configuration.md
> +The components and services included in the fragment appear inside a read-only fragment section in the **Components** and **SERVICES** sub-tab.
```suggestion
The components and services included in the fragment appear inside a read-only fragment section in the **Components** and **Services** sub-tab.

```

2023-04-18 14:16 UTC, npentrel commented on docs/manage/parts-and-remotes.md
> +To delete a sub-part or make it the main part, use the buttons in the top right of the **CONFIG** tab.
```suggestion
To delete a sub-part or make it the main part, use the buttons in the top right of the **config** tab.
```

2023-04-18 14:17 UTC, npentrel commented on docs/manage/parts-and-remotes.md
> +![The CONFIG tab of a robot's page noting the location of the Make main part and Delete Part buttons.](../img/parts-and-remotes/part-mgmt.png)
```suggestion
![The config tab of a robot's page noting the location of the Make main part and Delete Part buttons.](../img/parts-and-remotes/part-mgmt.png)
```

2023-04-18 18:20 UTC, npentrel commented on docs/manage/configuration.md
> +
```suggestion
```

2023-04-18 18:36 UTC, merged