DOCS-969: Rename radius_cluster_segmenter
viamrobotics/docs pull request #1628
Opened 2023-08-07 13:43 UTC by npentrel

2023-08-07 15:25 UTC, sguequierre requested changes
One typo otherwise lgtm

2023-08-07 15:25 UTC, sguequierre commented on docs/services/vision/segmentation.md
> +| `ground_angle_tolerance_degs` | Optional | A float that determines how strictly the found ground plane should match the `ground_plane_normal_vec`. For example, even if the ideal ground plane is pur
```suggestion
| `ground_angle_tolerance_degs` | Optional | A float that determines how strictly the found ground plane should match the `ground_plane_normal_vec`. For example, even if the ideal ground plane is purely flat, a rover may encounter slopes and hills. The algorithm should find a ground plane even if the found plane is at a slant, up to a certain point. <br> Default: `30.00` </br> |
```

(Opt. if we are still doing this with andrew's table format updates you could do this the same way in the column above!)

2023-08-07 16:11 UTC, bhaney commented on docs/services/vision/segmentation.md
> +| `ground_plane_normal_vec` | Optional | A `(x,y,z)` vector that represents the normal vector of the ground plane. Different cameras have different coordinate systems. For example, a lidar's ground p
Yes, these are the cartesian coordinates r3.vector. This is the arrow that points perpendicular to the ground plane.

2023-08-07 16:13 UTC, bhaney approved these changes

2023-08-08 13:16 UTC, npentrel commented on docs/services/vision/segmentation.md
> +    "ground_angle_tolerance_degs": <>
```suggestion
    "ground_angle_tolerance_degs": <number>
```

2023-08-08 13:16 UTC, npentrel commented on docs/services/vision/segmentation.md
> +    "ground_plane_normal_vec": <integer>,
```suggestion
        "ground_plane_normal_vec": {
          "x": <integer>,
          "y": <integer>,
          "z": <integer>
        },
```

2023-08-08 13:20 UTC, npentrel commented on docs/appendix/release-notes.md
> +You can replace existing Radius Clustering 3D segmenters by [configuring new ones in the UI](/services/vision/segmentation/#configure-a-obstacles_pointcloud) or you can update the [Raw JSON configura
```suggestion
You can replace existing Radius Clustering 3D segmenters by [configuring new ones in the UI](/services/vision/segmentation/#configure-an-obstacles_pointcloud) or you can update the [Raw JSON configuration of your robots](/manage/configuration/#the-config-tab):
```

2023-08-08 13:20 UTC, npentrel commented on docs/services/vision/segmentation.md
> +- [**Obstacles Pointcloud (`obstacles_pointcloud`)**](#configure-a-obstacles_pointcloud): A segmenter that identifies well separated objects above a flat plane.
```suggestion
- [**Obstacles Pointcloud (`obstacles_pointcloud`)**](#configure-an-obstacles_pointcloud): A segmenter that identifies well separated objects above a flat plane.
```

2023-08-09 10:18 UTC, merged