DOCS-1051: Add guidance on requirements.txt
viamrobotics/docs pull request #1712
Opened 2023-08-28 21:15 UTC by andf-viam

Add guidance on the required form of the `requirements.txt` file when building custom modules (for upload to the Registry).

2023-08-28 21:24 UTC, andf-viam commented
@Fahmina this is ready for review, latest staging link in the PR descr. Thanks!

2023-09-01 17:25 UTC, Fahmina requested changes
mostly LGTM. We simplified the contents of requirements.txt a ton to follow what we document in our python-module-example repo.

2023-09-01 17:25 UTC, Fahmina commented on docs/extend/modular-resources/create/_index.md
> +For example, a `requirements.txt` file with the following contents ensures that version `4.23.4` of `protobuf` and version `0.4.6` or later of the Viam Python SDK (`viam-sdk`) is installed:
```suggestion
For example, a `requirements.txt` file with the following contents ensures that the Viam Python SDK (`viam-sdk`) is installed. You may also add additional dependencies as needed:
```

2023-09-01 17:25 UTC, Fahmina commented on docs/extend/modular-resources/create/_index.md
> +viam-sdk >= 0.4.6 ; python_version >= "3.9"
```suggestion
viam-sdk
```

2023-09-01 18:49 UTC, Fahmina approved these changes
LGTM!!!

2023-09-05 15:37 UTC, merged