DOCS-1031: Clarify serial_path
viamrobotics/docs pull request #2119
Opened 2023-10-30 18:30 UTC by andf-viam

Clarify and standardize `serial_path` attributes description, and JSON examples that use them.

Notes: `dmesg` was the only cross-platform approach I found that worked in all cases, [approved by Matt D](https://github.com/viamrobotics/docs/pull/1596). But Rpi (or just Linux in general) is a much more likely use case, so it definitely makes sense to include direct instructions for that case everywhere. This PR is my attempt to balance both: platform specific initially (x2 for macOS), then platform agnostic-generally, in the hopes of casting a wide-enough net. LMK if you'd like to see `dmesg` disappear outright, however.

2023-10-30 21:07 UTC, stevebriskin requested changes

2023-10-30 21:07 UTC, stevebriskin commented on docs/components/motor/dmc4000.md
> +| `serial_path` | string | Optional | The full filesystem path to the serial device, starting with <file>/dev/</file>. To find your serial device path, first connect the serial device to your smart m
In this case (for dmc4000), the driver will actually try to auto-detect if a path is not provided.

2023-10-30 21:07 UTC, stevebriskin commented on docs/components/motor/roboclaw.md
> +| `serial_path` | string | Optional | The full filesystem path to the serial device, starting with <file>/dev/</file>. To find your serial device path, first connect the serial device to your smart m
serial_path is required for this driver.

2023-10-30 21:07 UTC, stevebriskin commented on docs/components/movement-sensor/gps/gps-nmea-rtk-serial.md
> +| `serial_path`            | string | Optional     | The full filesystem path to the serial device, starting with <file>/dev/</file>. To find your serial device path, first connect the serial device
It is required

2023-10-30 21:07 UTC, stevebriskin commented on docs/components/movement-sensor/imu/imu-wit.md
> +| `serial_path`      | string | Optional  | The full filesystem path to the serial device, starting with <file>/dev/</file>. To find your serial device path, first connect the serial device to your s
required

2023-10-30 21:07 UTC, stevebriskin commented on docs/components/power-sensor/renogy.md
> +| `serial_path` | string | Optional | The full filesystem path to the serial device, starting with <file>/dev/</file>. To find your serial device path, first connect the serial device to your smart m
Defaults to "/dev/serial0" if not provided.

2023-10-30 22:31 UTC, andf-viam commented
Thanks much! Changes made!

2023-10-31 17:32 UTC, npentrel commented on docs/components/movement-sensor/imu/imu-wit.md
> +| ------------------ | ------ | ------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------
nit
```suggestion
<!-- prettier-ignore -->
| Name               | Type   | Inclusion    | Description |
| -------------- | ------ | ----------- | ----------- |
```

2023-11-03 14:59 UTC, andf-viam commented
Hi @stevebriskin , let me know if you'd like to see any further changes. Thanks!

2023-11-09 20:38 UTC, stevebriskin approved these changes

2023-11-09 20:39 UTC, merged