DOCS-1508: Clarify fleet use case
viamrobotics/docs pull request #2315
Opened 2023-12-08 23:32 UTC by JessamyT

2023-12-11 16:27 UTC, npentrel requested changes
I think you can go further than that: 
Start in the first sentence "You can use Viam’s cloud-based fleet management tools to monitor and manage access to your fleet of smart machines." you can make that about an existing fleet. 

In the second paragraph and the step where you configure robots, add info that you can add management and this regardless of whether the machines are already running code. that this works alongside it. And that you can once you've added viam, use it for any of or all of data management, remote control, and code deployment. (Probably not in exactly those words ;))

2023-12-12 05:40 UTC, JessamyT commented
Between step 5 talking about data and the control tab, plus the registry sentence, I think the last point is addressed?

2023-12-13 11:28 UTC, npentrel commented on docs/use-cases/manage-fleet.md
> +Use these tools as you create and scale a new fleet of robots, or [integrate Viam](https://www.viam.com/post/integrate-your-ros2-robot-with-viam) to manage and add functionality to your existing flee
This is a good idea but I think remove the link here and add it to the next steps section instead. you can remove the tutorial one to make space

2023-12-13 11:33 UTC, npentrel commented on docs/use-cases/manage-fleet.md
> +Use these tools as you create and scale a new fleet of robots, or [integrate Viam](https://www.viam.com/post/integrate-your-ros2-robot-with-viam) to manage and add functionality to your existing flee
Nit - I think that helps understanding
```suggestion
Use these tools as you create and scale a new fleet of robots, or [integrate Viam](https://www.viam.com/post/integrate-your-ros2-robot-with-viam) to manage and add functionality like data management to your existing fleet.
```

2023-12-13 11:33 UTC, npentrel approved these changes
This looks good to me - would you mind adding Eliot to this review, just in case he wants to chime in?

2023-12-15 11:51 UTC, npentrel commented on docs/use-cases/manage-fleet.md
> +{{% manualcard link="https://www.viam.com/post/integrate-your-ros2-robot-with-viam/" target="_blank" %}}
```suggestion

<!-- markdownlint-disable MD034 -->

{{% manualcard link="https://www.viam.com/post/integrate-your-ros2-robot-with-viam/" target="_blank" %}}
```

2023-12-15 11:52 UTC, npentrel commented
Let's merge this and we can address any feedback from Eliot later. Just fixing the test

2023-12-15 12:28 UTC, merged