DOCS-1600: Add configure a fleet page
viamrobotics/docs pull request #2466
Opened 2024-02-03 00:21 UTC by JessamyT

2024-02-05 12:52 UTC, npentrel requested changes
Great start - a few things we can improve a little more

2024-02-05 20:09 UTC, JessamyT commented on docs/fleet/configure-a-fleet.md
> +Fragments are a way of sharing and managing [machine configurations](/build/configure) across multiple machines.
```suggestion
Fragments are a way of sharing and managing [machine configurations](/build/configure/) across multiple machines.
```

2024-02-06 12:42 UTC, npentrel commented on docs/fleet/configure-a-fleet.md
> +When changes are made to the fragment, the Viam app automatically applies the changes to all machines that include the fragment in their config.
```suggestion
When you or one of your collaborators changes the fragment, the Viam app automatically applies the changes to all machines that include the fragment in their config.
```

2024-02-06 12:44 UTC, npentrel commented on docs/fleet/configure-a-fleet.md
> +   You can get the JSON configuration from the [**CONFIG** tab](/build/configure/#the-config-tab) of your first machine by switching to **Raw JSON** mode.
that sounds good too

2024-02-06 20:22 UTC, merged