DOCS-1407: Add viam module generator / README template to create page
viamrobotics/docs pull request #2473
Opened 2024-02-05 18:44 UTC by sguequierre

* Add instruction to use generator (necessary to fully use template) and instruction that just points to template

2024-02-09 12:36 UTC, npentrel commented on docs/registry/create/_index.md
> +Strings surrounded by `<%= %>` indicate variables that you should replace with the appropriate values.
I think it makes sense to indicate variables that need replacing in the same way we do across code samples in the docs.

2024-02-09 12:37 UTC, npentrel commented on docs/registry/create/_index.md
> +```bash
I'm not sure if you need to escape these?

2024-02-09 12:37 UTC, npentrel commented on docs/registry/create/_index.md
> +````
what are these 4 here?

2024-02-09 12:38 UTC, npentrel requested changes
please make sure PRs build before sending for review

2024-02-09 15:14 UTC, sguequierre commented on docs/registry/create/_index.md
> +# <INSERT NAME> modular service
```suggestion
# <INSERT NAME> modular resource
```

2024-02-13 10:41 UTC, npentrel commented on docs/registry/create/_index.md
> +Strings surrounded by `<%= %>` indicate variables that you should replace with the appropriate values.
```suggestion
Strings of the form `<INSERT X>` indicate variables that you should replace with the appropriate values.
```

2024-02-13 10:41 UTC, npentrel approved these changes
LGTM % remaining change

2024-02-13 21:57 UTC, merged