Update readme template and add example
viamrobotics/docs pull request #2552
Opened 2024-02-20 11:28 UTC by npentrel

2024-02-20 11:34 UTC, npentrel commented on docs/registry/create/_index.md
> +Navigate to the **Config** tab of your robot’s page in [the Viam app](https://app.viam.com/). Click on the **Components** subtab and click **Create component**. Select the `base` type, then select th
```suggestion
Navigate to the **Config** tab of your robot’s page in [the Viam app](https://app.viam.com/). Click on the **Components** subtab and click **Create component**. Select the `base` type, then select the `agilex-limo` model. Click **Add module**, then enter a name for your base and click **Create**.
```

2024-02-20 15:50 UTC, sguequierre requested changes

2024-02-20 15:50 UTC, sguequierre commented on docs/registry/create/_index.md
> +## Build and Run
```suggestion
## Build and run
```
To keep headings rule like docs

2024-02-20 15:50 UTC, sguequierre commented on docs/registry/create/_index.md
> +Navigate to the **Config** tab of your robot’s page in [the Viam app](https://app.viam.com/). Click on the **Components** subtab and click **Create component**. Select the `base` type, then select th
```suggestion
Navigate to the **Config** tab of your machine’s page in [the Viam app](https://app.viam.com/). Click on the **Components** subtab and click **Create component**. Select the `base` type, then select the `agilex-limo` model. Click **Add module**, then enter a name for your base and click **Create**.
```
Did change in template

2024-02-20 15:50 UTC, sguequierre commented on docs/registry/create/_index.md
> +> Before configuring your base, you must [create a robot](https://docs.viam.com/manage/fleet/robots/#add-a-new-robot).
```suggestion
> Before configuring your base, you must [create a machine](https://docs.viam.com/manage/fleet/robots/#add-a-new-robot).
```

2024-02-20 15:50 UTC, sguequierre commented on docs/registry/create/_index.md
> +> For more information, see [Configure a Robot](https://docs.viam.com/manage/configuration/).
```suggestion
> For more information, see [Configure a Machine](https://docs.viam.com/manage/configuration/).
```

2024-02-20 15:50 UTC, sguequierre commented on docs/registry/create/_index.md
> +## Next Steps
```suggestion
## Next steps
```

2024-02-20 15:50 UTC, sguequierre commented on docs/registry/create/_index.md
> +## Local Development
```suggestion
## Local development
```

2024-02-21 19:14 UTC, sguequierre commented on docs/registry/create/_index.md
> +This module implements the <INSERT API NAMESPACE> <INSERT API NAME> API in a <INSERT MODEL> model.
nice

2024-02-21 19:14 UTC, sguequierre commented on docs/registry/create/_index.md
> +Click **Add module**, then enter a name for your <INSERT API NAME> and click **Create**.
Good catch

2024-02-21 19:14 UTC, sguequierre approved these changes

2024-02-21 21:33 UTC, merged