DOCS-1798: Add performance metrics capture
viamrobotics/docs pull request #2607
Opened 2024-03-01 18:15 UTC by npentrel

2024-03-01 18:28 UTC, npentrel commented on docs/data/capture/performance-metrics.md
> +- **Network Traffic**: Detailed network statistics, including bytes sent and received, packet information, and error counts, provide a deep dive into a device's network performance.
```suggestion
- **Wireless Signal Strength and Quality**: signal level, link quality, and noise level
- **Memory Usage**: memory statistics, including total available memory, used percentage, and specifics on various types of memory (cached, free, slab, etc.)
- **CPU Utilization**: CPU usage across different states (user, system, idle, etc.)
- **Disk I/O**: metrics on read and write operations, including bytes transferred and operation times
- **Network Traffic**: detailed network statistics, including bytes sent and received, packet information, and error counts, provide a deep dive into a device's network performance.
```

2024-03-26 16:45 UTC, sguequierre requested changes
This is very cool-- some small fixes and suggestions otherwise LGTM!

2024-03-26 16:45 UTC, sguequierre commented on docs/data/capture/performance-metrics.md
> +- **Network Traffic**: detailed network statistics, including bytes sent and received, packet information, and error counts, provide a deep dive into a device's network performance
```suggestion
- **Network Traffic**: detailed network statistics, including bytes sent and received, packet information, and error counts, providing a deep dive into a device's network performance
```

2024-03-26 16:45 UTC, sguequierre commented on docs/data/capture/performance-metrics.md
> +To capture data from a machine, you need to [create a machine in Viam](https://docs.viam.com/manage/fleet/machines/#add-a-new-machine) and follow the setup instruction to install `viam-server` and co
```suggestion
To capture data from a machine, you need to [create a machine in Viam](https://docs.viam.com/manage/fleet/machines/#add-a-new-machine) and follow the setup instructions to install `viam-server` and connect it to the Viam app.
```
I think

2024-03-26 16:45 UTC, sguequierre commented on docs/data/capture/performance-metrics.md
> +The module provides a `sensor` that allows you to obtain readings containing your machine's performance metrics.
```suggestion
The module provides a [sensor](/components/sensor/) that allows you to obtain readings containing your machine's performance metrics.
```
(opt)

2024-03-26 16:45 UTC, sguequierre commented on docs/data/capture/performance-metrics.md
> +In the next step you will configure the data manager to capture and sync the performance metrics from your configured sensor.
(opt) I would veer on the side of referring to it as data management service consistently. Also not sure if this sentence is necessary although it does provide a bit of a transition. Maybe consider line 43 before 41?

2024-03-26 16:45 UTC, sguequierre commented on docs/data/capture/performance-metrics.md
> +To capture the data from your configured sensor, you need to add the data management service and configure it to capture and sync the sensor data:
```suggestion
To capture the data from your configured sensor, you need to add the [data management service](https://docs.viam.com/data/) and configure it to capture and sync the sensor data:
```
(opt)

2024-03-26 16:45 UTC, sguequierre commented on docs/data/capture/performance-metrics.md
> +   For example `data_manager`.
```suggestion
   For example, `data_manager`.
```
I think although maybe fine?

2024-03-26 16:45 UTC, sguequierre commented on docs/data/capture/performance-metrics.md
> +4. Go to the **Components** subtab and find your telegrafsensor.
```suggestion
4. Go to the **Components** subtab and find your `telegrafsensor`'s configuration card.
```
(opt)

2024-03-26 16:45 UTC, sguequierre commented on docs/data/capture/performance-metrics.md
> +Once you have captures data about your machines, you can query your captured data with any tools that with SQL or MQL or visualize your data with tools like Grafana:
```suggestion
Once you have captured data about your machines, you can query your captured data with any tools that with SQL or MQL or visualize your data with tools like Grafana:
```

2024-03-26 17:40 UTC, npentrel commented on docs/data/capture/performance-metrics.md
> +For more information, see [add a module from the Viam Registry](https://docs.viam.com/registry/configure/#add-a-modular-resource-from-the-viam-registry).
```suggestion
For more information, see [add a module from the Viam Registry](https://docs.viam.com/registry/configure/#add-a-modular-resource-from-the-viam-registry).

In the next step you will configure the data management service to capture and sync the performance metrics from your configured sensor.
```

2024-03-26 17:40 UTC, npentrel commented on docs/data/capture/performance-metrics.md
> +## Configure data manager to capture and sync sensor data
```suggestion
## Configure data management service to capture and sync sensor data
```

2024-03-26 17:42 UTC, npentrel commented
@sguequierre ready for re-review

2024-03-26 18:54 UTC, sguequierre approved these changes

2024-03-27 13:40 UTC, merged