DOCS-1489: Change Python virtual environment string
viamrobotics/docs pull request #2670
Opened 2024-03-15 00:14 UTC by JessamyT

2024-03-15 00:14 UTC, JessamyT commented on docs/build/program/python-venv.md
> +Inside the activated `.venv Python environment, you can now install the Viam Python SDK:
```suggestion
Inside the activated `.venv` Python environment, you can now install the Viam Python SDK:
```

2024-03-15 11:32 UTC, npentrel requested changes
This is good but the ticket indicates they changed the in app code sample page which we'll need to update [here](https://docs.viam.com/build/program/#requirements).

<img width="921" alt="Screenshot 2024-03-15 at 12 28 35" src="https://github.com/viamrobotics/docs/assets/5212232/abc6b6fe-78d3-4c83-8bfb-e2061c7df786">

2024-03-15 14:13 UTC, hexbabe approved these changes

2024-03-15 18:26 UTC, JessamyT commented
@npentrel Are you saying that on the #requirements section there, instead of just linking to setting up a virtual environment, we should actually include the commands to do so on that Program page as well? Can do.

2024-03-16 01:12 UTC, JessamyT commented
Should we update https://python.viam.dev/ too?

2024-03-18 13:40 UTC, npentrel approved these changes

2024-03-18 21:07 UTC, merged