DOCS-1915: Revert changes for fragments
viamrobotics/docs pull request #3215
Opened 2024-08-07 17:52 UTC by sguequierre

* Revert changes for fragments

Couldn't get this to work on my own, asked question to resolve but for now going off of diagram demo

2024-08-07 17:53 UTC, sguequierre commented on docs/fleet/fragments.md
> +- Revert changes made from the fragment overwrite
```suggestion
- Revert changes made from the fragment overwrite.
```

2024-08-07 19:47 UTC, JessamyT requested changes
So, I don't think this is accurate. I think what the eng change is, is if you make fragment mods, you can revert them back to the original fragment (i.e. remove the fragment mods).

Rather than adding revert fragment mods as a separate option for overwriting a fragment, it'd be more like, once you use fragment mods using the builder UI (which this page also needs to be updated with), you can *then* revert the mods you just made.

I think it'd make more sense to update the fragments doc with the new easy (builder) way of mod-ing fragments first, before talking about reverting.

2024-08-07 20:59 UTC, sguequierre commented
> So, I don't think this is accurate. I think what the eng change is, is if you make fragment mods, you can revert them back to the original fragment (i.e. remove the fragment mods).
> 
> Rather than adding revert fragment mods as a separate option for overwriting a fragment, it'd be more like, once you use fragment mods using the builder UI (which this page also needs to be updated with), you can _then_ revert the mods you just made.
> 
> I think it'd make more sense to update the fragments doc with the new easy (builder) way of mod-ing fragments first, before talking about reverting.
> 
> ![image](https://private-user-images.githubusercontent.com/75634662/355964003-fbc43647-de13-4f94-8b05-085ad9d33131.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjQ2MDUsIm5iZiI6MTcyMzA2NDMwNSwicGF0aCI6Ii83NTYzNDY2Mi8zNTU5NjQwMDMtZmJjNDM2NDctZGUxMy00Zjk0LThiMDUtMDg1YWQ5ZDMzMTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDIwNTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZDQxMGUxYTJkZGUwN2YzNzhiMTI0ZTYyZGU2YzdkMzUwYjY2MDIyZDQ4ZmNiZmY5ZTY5NGYwZDVlYjRjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zJVz7A9TYmymTi9xBt5JMpSOhmXmp3u01UmPrEh-6Uk)
> 
> Edit: I'm working on related content right now so if you'd like me to roll this into that lmk!

Ok, thank you, this makes sense with the confusion I had! I will update this to clarify.

2024-08-07 23:22 UTC, JessamyT commented
So sorry if you've already put time into updating this but, I think it is actually covered by https://github.com/viamrobotics/docs/pull/3201. When I went to de-duplicate content I realized it made more sense to just update in both the how-to and the existing page.

2024-08-08 15:51 UTC, sguequierre commented
> So sorry if you've already put time into updating this but, I think it is actually covered by #3201. When I went to de-duplicate content I realized it made more sense to just update in both the how-to and the existing page.

No I haven't yet, so thank you for letting me know-- I can close this if that's ok! Thank you for your work on this!

2024-08-08 22:11 UTC, closed without merging