DOCS-2786: Improve viam-micro-server setup guide
viamrobotics/docs pull request #3370
Opened 2024-08-30 11:39 UTC by npentrel

2024-08-30 11:40 UTC, npentrel commented on docs/installation/micro-rdk-dev.md
> ----
This is mostly a rename, not sure why it's not picking up on that.

2024-09-03 14:45 UTC, sguequierre requested changes
Fixing some moments where micro-RDK is still used

2024-09-03 14:45 UTC, sguequierre commented on docs/architecture/viam-micro-server.md
> +If you want to extend the functionality of `viam-micro-server` or customize it, see the development setup guide.
```suggestion
If you want to access camera functionality, extend the functionality of `viam-micro-server, or customize it see the development setup guide.
```
Might be worth clarifying that here

2024-09-03 14:45 UTC, sguequierre commented on docs/components/camera/esp32-camera.md
> +Finish the [Micro-RDK Development Setup](/installation/viam-micro-server-dev/) and return to this guide.
```suggestion
Finish the [`viam-micro-server` Development Setup](/installation/viam-micro-server-dev/) and return to this guide.
```

2024-09-03 14:45 UTC, sguequierre commented on docs/components/camera/esp32-camera.md
> +To use this model, you must follow the [Micro-RDK Development Setup](/installation/viam-micro-server-dev/), which enables you to install and activate the ESP-IDF.
```suggestion
To use this model, you must follow the [`viam-micro-server` Development Setup](/installation/viam-micro-server-dev/), which enables you to install and activate the ESP-IDF.
```

2024-09-03 14:45 UTC, sguequierre commented on docs/installation/viam-micro-server-dev.md
> +To set up the Docker development environment for ESP manually, complete the following instructions:
```suggestion
To set up the Docker development environment for ESP32 manually, complete the following instructions:
```
Just bc we don't tend to refer to it as ESP (espressif)

2024-09-03 14:45 UTC, sguequierre commented on docs/installation/viam-micro-server-dev.md
> +1. Generate a new project from [this template](https://github.com/viamrobotics/micro-rdk/tree/main/templates/project) to create a new micro-RDK project to upload to your ESP32 by running:
```suggestion
1. Generate a new project from [this template](https://github.com/viamrobotics/micro-rdk/tree/main/templates/project) to create a new `viam-micro-server` project to upload to your ESP32 by running:
```

2024-09-03 20:44 UTC, npentrel commented
Since feedback was fairly minimal, going to merge, that should make the other viam-micro-server ticket easier.

2024-09-03 20:44 UTC, merged