DOCS-582: Mark robot service page as draft
viamrobotics/docs pull request #829
Opened 2023-03-17 15:32 UTC by sguequierre

* make it a draft it case we want to redocument these methods soon

2023-03-24 16:30 UTC, edaniels commented on docs/viam/_index.md
> +- [Robot](https://github.com/viamrobotics/rdk/blob/main/robot/server/server.go) provides high level robot commands
this shouldn't for the same reason I mentioned in the other comment

2023-03-24 17:00 UTC, edaniels requested changes
See new comment

2023-03-24 17:41 UTC, sguequierre commented on docs/viam/_index.md
> +- [Robot](https://github.com/viamrobotics/rdk/blob/main/robot/server/server.go) provides high level robot commands
@edaniels Sorry for the confusion, what do you mean? Shouldn't link to /server go here? Should I remove the bullet entirely?

2023-03-24 19:49 UTC, npentrel commented on docs/viam/_index.md
> +- [Robot](https://github.com/viamrobotics/rdk/blob/main/robot/server/server.go) provides high level robot commands
Leaning towards removing the bullet point for now. But @edaniels can decide.

2023-03-27 15:02 UTC, sguequierre commented on docs/viam/_index.md
> +- [Robot](https://github.com/viamrobotics/rdk/blob/main/robot/server/server.go) provides high level robot commands
```suggestion
```

2023-03-27 15:03 UTC, sguequierre commented on docs/viam/_index.md
>  There are four categories of APIs:
```suggestion
There are three categories of APIs:
```

2023-03-27 15:04 UTC, sguequierre commented on docs/viam/_index.md
> +- [Robot](https://github.com/viamrobotics/rdk/blob/main/robot/server/server.go) provides high level robot commands
Github is not working

2023-03-29 11:46 UTC, edaniels requested changes

2023-03-29 11:46 UTC, edaniels commented on docs/viam/_index.md
> +- [Robot](https://github.com/viamrobotics/rdk/blob/main/robot/server/server.go) provides high level robot commands
We should link to our docs on robot proto

2023-03-29 12:06 UTC, npentrel commented on docs/viam/_index.md
> +- [Robot](https://github.com/viamrobotics/rdk/blob/main/robot/server/server.go) provides high level robot commands
Do you mean https://pkg.go.dev/go.viam.com/rdk@v0.2.31/robot ? I don't think we have any others.

2023-03-29 12:08 UTC, edaniels commented on docs/viam/_index.md
> +- [Robot](https://github.com/viamrobotics/rdk/blob/main/robot/server/server.go) provides high level robot commands
There's https://github.com/viamrobotics/api/blob/main/proto/viam/robot/v1/robot.proto.

2023-03-29 16:02 UTC, sguequierre commented on docs/viam/_index.md
> +- [Robot](https://github.com/viamrobotics/rdk/blob/main/robot/server/server.go) provides high level robot commands
@edaniels Have now made this revision in https://github.com/viamrobotics/docs/pull/912 if you want to give it a look! This pr is left over on old fork from last week's change with the docs being made public, 912 is what can be merged

2023-03-29 16:25 UTC, edaniels commented
we should update title of this PR

2023-03-30 13:50 UTC, closed without merging